#!/bin/sh -eu

filesize() {
  LC_ALL=C ls -nL -- "$1" | { read a b c d size e ; echo "$size" ; }
}

checkhash() {
  case "${1%%:*}" in
    MD5Sum)
      echo "${1##*:} *$2" | tee | md5sum --quiet -c -
      return $?
      ;;
    *)
      echo "Unknown hash $1" >&2
      exit 1
      ;;
  esac
}

sed "s,^'\([^']*\)' \([^ ]*\) \([0-9]*\) \([^ ]*\)$,\2 \3 \4 \1," < uris | while read filename size sum uri ; do
  test -e "$filename" && checkhash "$sum" "$filename" && continue
  curl --retry 20 -C - -o "$filename" "$uri"
done

