#!/bin/sh -eu

filesize() {
  LC_ALL=C ls -nL -- "$1" | { read a b c d size e ; echo "$size" ; }
}

sed "s,^'\([^']*\)' \([^ ]*\) \([0-9]*\) \([^ ]*\)$,\2 \3 \4 \1," < uris | while read filename size sum uri ; do
  if [ -e "$filename" ] ; then
    test $( filesize "$filename" ) -eq $size && continue
  fi
  curl --retry 20 -C - -o "$filename" "$uri"
done

